// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACLFy4XSMxT2kwkiJ0wpnB24WaESiimcA',
    appId: '1:1041843153885:web:cdb0a5fc6114f17c156434',
    messagingSenderId: '1041843153885',
    projectId: 'tiktok-kg',
    authDomain: 'tiktok-kg.firebaseapp.com',
    storageBucket: 'tiktok-kg.appspot.com',
    measurementId: 'G-34NT74Z23D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexFOZAc_6m-Pcqke6SnfdO_wc7CRuYNs',
    appId: '1:1041843153885:android:b4656de54e56d2f5156434',
    messagingSenderId: '1041843153885',
    projectId: 'tiktok-kg',
    storageBucket: 'tiktok-kg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6nWaO707-25h9_GIiQtyWP2QkaJ1TMx0',
    appId: '1:1041843153885:ios:0d5eca9ce9fc1e42156434',
    messagingSenderId: '1041843153885',
    projectId: 'tiktok-kg',
    storageBucket: 'tiktok-kg.appspot.com',
    iosBundleId: 'com.example.tikTok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6nWaO707-25h9_GIiQtyWP2QkaJ1TMx0',
    appId: '1:1041843153885:ios:0d5eca9ce9fc1e42156434',
    messagingSenderId: '1041843153885',
    projectId: 'tiktok-kg',
    storageBucket: 'tiktok-kg.appspot.com',
    iosBundleId: 'com.example.tikTok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACLFy4XSMxT2kwkiJ0wpnB24WaESiimcA',
    appId: '1:1041843153885:web:11f152cb571de595156434',
    messagingSenderId: '1041843153885',
    projectId: 'tiktok-kg',
    authDomain: 'tiktok-kg.firebaseapp.com',
    storageBucket: 'tiktok-kg.appspot.com',
    measurementId: 'G-3XTF2DGTC7',
  );
}
