// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_-p2s2urah7dkGQDQR6z0SQ-NrV6Sjg',
    appId: '1:720760813744:web:6902cdaf0bec5b030f2375',
    messagingSenderId: '720760813744',
    projectId: 'tiktok-kg-5f7cc',
    authDomain: 'tiktok-kg-5f7cc.firebaseapp.com',
    storageBucket: 'tiktok-kg-5f7cc.appspot.com',
    measurementId: 'G-2RMHK48FGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2LmeTKLWQS6ZMKOVUbU7pFhDI-hKSq2M',
    appId: '1:720760813744:android:7ba6381847fd54ed0f2375',
    messagingSenderId: '720760813744',
    projectId: 'tiktok-kg-5f7cc',
    storageBucket: 'tiktok-kg-5f7cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzo1wkMDrD8jEL_w_teFBxutNAq1Ao6Hc',
    appId: '1:720760813744:ios:bac5faf20215c06c0f2375',
    messagingSenderId: '720760813744',
    projectId: 'tiktok-kg-5f7cc',
    storageBucket: 'tiktok-kg-5f7cc.appspot.com',
    iosBundleId: 'com.example.tikTok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzo1wkMDrD8jEL_w_teFBxutNAq1Ao6Hc',
    appId: '1:720760813744:ios:bac5faf20215c06c0f2375',
    messagingSenderId: '720760813744',
    projectId: 'tiktok-kg-5f7cc',
    storageBucket: 'tiktok-kg-5f7cc.appspot.com',
    iosBundleId: 'com.example.tikTok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl_-p2s2urah7dkGQDQR6z0SQ-NrV6Sjg',
    appId: '1:720760813744:web:4ea07ad89aec0d920f2375',
    messagingSenderId: '720760813744',
    projectId: 'tiktok-kg-5f7cc',
    authDomain: 'tiktok-kg-5f7cc.firebaseapp.com',
    storageBucket: 'tiktok-kg-5f7cc.appspot.com',
    measurementId: 'G-0NQLKPEWEN',
  );

}